#DROP DATABASE EMP;
CREATE DATABASE EMP;
USE EMP;
CREATE TABLE EMPLOYEE (
id int NOT NULL,
first_name varchar(20) DEFAULT NULL,
last_name varchar(20) DEFAULT NULL,
PRIMARY KEY (id)
);
SELECT * FROM EMP.EMPLOYEE;
DELETE FROM EMP.EMPLOYEE WHERE first_name = 'Yashpal';
